name: Generate Sidebar

on: [push, workflow_dispatch]

permissions: write-all

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Script
        run: |
          sh marketplace/scripts/action.sh
      - name: Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit -m "generate market content" -a || exit 0
          git push
